name: Jekyll site CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - name: Install somthing.
      run: bundle install

    steps:
    - name: Build Project.
      run: |
          bundle exec jekyll build
